site_name: Cours de programmation en sciences
site_url: https://profdenis.github.io/sn1_doc
repo_name: profdenis/sn1_doc
repo_url: https://github.com/profdenis/sn1_doc
nav:
  - Accueil: index.md
  - Introduction:
    - introduction/index.md
    - 2. Histoire de la programmation: introduction/histoire.md
    - introduction/algorithmes.md
    - introduction/exécution.md
  - Section 1:
    - section1/01_affichage.md
    - section1/02_entrées.md
    - section1/03_modules.md
    - section1/04_fonctions.md
    - Exercices:
      - section1/exercices/01_exercices.md
      - section1/exercices/02_exercices.md
      - section1/exercices/03_exercices.md
      - section1/exercices/04_exercices.md
    - Corrigés:
      - section1/corrigés/01_corrigés.md
      - section1/corrigés/02_corrigés.md
      - section1/corrigés/03_corrigés.md
      - section1/corrigés/04_corrigés.md
  - Section 2:
    - section2/01_bool.md
    - section2/02_conditionnelles.md
    - section2/03_match.md
    - section2/04_while.md
    - section2/05_for.md
    - section2/06_structures-imbriquées.md
    - Exercices:
      - section2/exercices/01_exercices.md
      - section2/exercices/02_exercices.md
      - section2/exercices/03_exercices.md
      - section2/exercices/04_exercices.md
      - section2/exercices/05_exercices.md
      - section2/exercices/06_exercices.md
    - Corrigés:
      - section2/corrigés/01_corrigés.md
      - section2/corrigés/02_corrigés.md
      - section2/corrigés/03_corrigés.md
      - section2/corrigés/04_corrigés.md
      - section2/corrigés/05_corrigés.md
      - section2/corrigés/06_corrigés.md
  - Section 3:
    - section3/01_exceptions.md
    - section3/02_listes.md
    - section3/03_chaines.md
    - section3/04_fichiers.md
    - section3/05_dictionnaires.md
    - Exercices:
      - section3/exercices/01_exercices.md
      - section3/exercices/02_exercices.md
      - section3/exercices/03_exercices.md
      - section3/exercices/04_exercices.md
      - section3/exercices/05_exercices.md
    - Corrigés:
      - section3/corrigés/01_corrigés.md
      - section3/corrigés/02_corrigés.md
      - section3/corrigés/03_corrigés.md
      - section3/corrigés/04_corrigés.md
      - section3/corrigés/05_corrigés.md
  - Section 4:
    - section4/01_numpy.md
    - section4/02_pyplot.md
    - Exercices:
      - section4/exercices/01_exercices.md
      - section4/exercices/02_exercices.md
    - Corrigés:
      - section4/corrigés/01_corrigés.md
      - section4/corrigés/02_corrigés.md


theme:
  name: material
  locale: fr
  language: fr
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    logo: material/language-python
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


extra_css:
  - style.css

markdown_extensions:
    smarty: { }
    toc:
      permalink: true
    sane_lists: { }
    admonition: { }
    attr_list: {}
    pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
    pymdownx.inlinehilite: { }
    pymdownx.snippets: {}
    pymdownx.superfences: { }
    pymdownx.fancylists: { }
    pymdownx.saneheaders: { }
    pymdownx.mark: { }
    pymdownx.tabbed: { }
    pymdownx.tasklist: { }
    pymdownx.tilde: { }
    pymdownx.details: { }
    pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        theme:
          enabled: false
    - search: {}