site_name: Cours de programmation en sciences
site_url: https://profdenis.github.io/sn1_doc
repo_name: profdenis/sn1_doc
repo_url: https://github.com/profdenis/sn1_doc

nav:
  - Accueil: index.md
  - Introduction:
    - introduction/index.md
    - Histoire de la programmation: introduction/histoire.md
    - introduction/algorithmes.md
    - introduction/exécution.md
  - Section 1:
    - section1/affichage.md
    - section1/entrées.md
    - section1/modules.md
    - section1/fonctions.md
    - Exercices:
      - section1/exercices/exercices1.md
      - section1/exercices/exercices2.md
      - section1/exercices/exercices3.md
      - section1/exercices/exercices4.md
    - Corrigés:
      - section1/corrigés/exercices1-corrigés.md
      - section1/corrigés/exercices2-corrigés.md
      - section1/corrigés/exercices3-corrigés.md
      - section1/corrigés/exercices4-corrigés.md
  - Section 2:
    - section2/bool.md
    - section2/conditionnelles.md
    - section2/match.md
    - section2/for.md
    - section2/while.md
    - section2/boucles-imbriquées.md
    - Exercices:
      - section2/exercices/exercices1.md
      - section2/exercices/exercices2.md
      - section2/exercices/exercices3.md
      - section2/exercices/exercices4.md
      - section2/exercices/exercices5.md
    - Corrigés:
      - section2/corrigés/exercices1-corrigés.md
      - section2/corrigés/exercices2-corrigés.md
      - section2/corrigés/exercices3-corrigés.md
      - section2/corrigés/exercices4-corrigés.md
      - section2/corrigés/exercices5-corrigés.md
  - Section 3:
    - section3/exceptions.md
    - section3/listes.md
    - section3/fichiers.md
    - section3/dictionnaires.md
  - Section 4:
    - section4/numpy.md
    - section4/pyplot.md



theme:
  name: material
  locale: en
  language: en
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


extra_css:
  - style.css

markdown_extensions:
    smarty: { }
    toc:
      permalink: true
    sane_lists: { }
    admonition: { }
    pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
    pymdownx.inlinehilite: { }
    pymdownx.snippets: {}
    pymdownx.superfences: { }
    pymdownx.fancylists: { }
    pymdownx.saneheaders: { }
    pymdownx.mark: { }
    pymdownx.tabbed: { }
    pymdownx.tasklist: { }
    pymdownx.tilde: { }
    pymdownx.details: { }
    pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        theme:
          enabled: false
    - search: {}